package edu.utap.firenote.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class Matchmaker(
    // AuthWrap information
    var count: Int = 0,
    var person1UUID: String = "",
    var person1Name: String = "",
    var person2UUID: String = "",
    var person2Name: String = "",

    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
