package edu.utap.firenote.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class Message(
    // AuthWrap information
    var name: String = "",
    var senderUID: String = "",
    var receiverUID: String = "",
    // Text
    var text: String = "",

    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
